
package com.ibm.was.wssample.sei.ping;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PingService", targetNamespace = "http://com/ibm/was/wssample/sei/ping/", wsdlLocation = "file:/C:/Applications/cygwin64/home/brobert/Developer/scalaWSDL/ping.wsdl")
public class PingService
    extends Service
{

    private final static URL PINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.ibm.was.wssample.sei.ping.PingService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.ibm.was.wssample.sei.ping.PingService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Applications/cygwin64/home/brobert/Developer/scalaWSDL/ping.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Applications/cygwin64/home/brobert/Developer/scalaWSDL/ping.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        PINGSERVICE_WSDL_LOCATION = url;
    }

    public PingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService() {
        super(PINGSERVICE_WSDL_LOCATION, new QName("http://com/ibm/was/wssample/sei/ping/", "PingService"));
    }

    /**
     * 
     * @return
     *     returns PingServicePortType
     */
    @WebEndpoint(name = "PingServicePort")
    public PingServicePortType getPingServicePort() {
        return super.getPort(new QName("http://com/ibm/was/wssample/sei/ping/", "PingServicePort"), PingServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PingServicePortType
     */
    @WebEndpoint(name = "PingServicePort")
    public PingServicePortType getPingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/ibm/was/wssample/sei/ping/", "PingServicePort"), PingServicePortType.class, features);
    }

}
